version: '2'

services:  
  db:
    image: "postgres:11"
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=inmates_data
    ports:
      - "65432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    container_name: "redis"

  aqueduct-server:
    container_name: "inmates-server"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - db
      - redis
    depends_on: 
      - db
      - redis
    ports:
    - "80:80"


### Note to self:
### READ: Startup order of docker
### Try/ catch surround the db connect with retries logic.

## Commands:
# docker compose config
# docker-compose up -d 
# docker-compose ps
# docker-compose down
# docker-compose logs


### db migrations
# aqueduct db upgrade --connect postgres://user-from-config-yaml:password-from-config-yaml@hostname:65432/db-from-config-yaml

# ormconfig.docker.json ???

## Scaling to multiple (4 instances for example)
# docker-compose up -d --scale db=4